set nocompatible
syntax on
set number
set ruler
set visualbell
set encoding=utf-8
set wrap
set showmode
set showcmd
set t_Co=256
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
